### ISSUE TITLE
Regenerate mapnificent.pb.go using updated goprotobuf

### ISSUE THREAD

**Issue by nhynes** [mapnificent/mapnificent_generator#1]
The golang protobuf project has moved from code.google.com to [github](https://github.com/golang/protobuf), which breaks the `import` in `mapnificent.pb.go`. This is easily fixed by regenerating the file:

``` diff
-import proto "code.google.com/p/goprotobuf/proto"
+import proto "github.com/golang/protobuf/proto"
```

**Comment by nhynes** [comment]
Sorry, didn't realize when I posted just how alpha this was!

**Comment by nikolauskrismer** [comment]
Why is this closed?
Just because the project is still alpha?
I am struggling with the same thing right now (is there a solution)?
